import "./node_modules/@sablier/devkit/just/base.just"

# ---------------------------------------------------------------------------- #
#                                    RECIPES                                   #
# ---------------------------------------------------------------------------- #

# Default recipe
default:
    @just --list

# Build the project
[group("app")]
build:
    na tsc

# Start development mode with file watching
[group("app")]
dev:
    na tsc --watch

# Run tests
[group("tests")]
@test *args:
    na vitest run {{ args }}
alias t := test

# Run tests with UI
[group("tests")]
@test-ui *args:
    na vitest --ui {{ args }}
alias tui := test-ui
